/**
 * @file
 *
 * Implemention of FreeRTOS-CLI "print_datetime" command.
 */

#include <stdio.h>
#include <stdlib.h>

#include "FreeRTOS.h"
#include "FreeRTOS_CLI.h"
#include "cmsis_os.h"

#include "main.h"

#include "console/commands.hpp"

#include "defines/rtc.hpp"
#include "defines/status.hpp"

#include "drivers/rtc.hpp"

#include "helpers/buffer_printer.hpp"
#include "helpers/cmsis_os.hpp"

#if not defined(SYSTEM_RTC) or not defined(SYSTEM_RTC_MUTEX)
#error "System RTC preprocessor defines must be specified.
#endif

namespace console::commands {

extern "C" RTC_HandleTypeDef RTC_HANDLE_NAME(SYSTEM_RTC);
extern "C" osMutexId_t RTC_MUTEX_HANDLE_NAME(SYSTEM_RTC_MUTEX);

static cmsis_os::Mutex RTC_MUTEX(RTC_MUTEX_HANDLE_NAME(SYSTEM_RTC_MUTEX));
static drivers::RealTimeClock REAL_TIME_CLOCK(RTC_HANDLE_NAME(SYSTEM_RTC), RTC_MUTEX);

/* This function implements the behaviour of a command, so must have the correct
prototype. */
BaseType_t run_print_datetime(
    char* write_buffer, size_t write_buffer_len, const char* command_string)
{
    /* For simplicity, this function assumes the output buffer is large enough
    to hold all the text generated by executing the vTaskList() API function,
    so the xWriteBufferLen parameter is not used. */
    UNUSED(write_buffer_len);

    RTC_DateTypeDef date = {};
    if (REAL_TIME_CLOCK.get_date(date) != defines::Status::OK) {
        snprintf(write_buffer, write_buffer_len, "Failed to get RTC.\r\n\r\n");
        return pdFALSE;
    }

    RTC_TimeTypeDef time = {};
    if (REAL_TIME_CLOCK.get_time(time) != defines::Status::OK) {
        snprintf(write_buffer, write_buffer_len, "Failed to get RTC.\r\n\r\n");
        return pdFALSE;
    }

    const char* format = "%02d-%02d-%04d %02d:%02d:%02d\r\n\r\n";
    snprintf(write_buffer, write_buffer_len, format, date.Month, date.Date,
        date.Year + 2000, time.Hours, time.Minutes, time.Seconds);
    return pdFALSE;
}

const CLI_Command_Definition_t print_datetime = { "print_datetime",
    "print_datetime: Print the RTC datetime.\r\n", run_print_datetime, 0 };

} // namespace console::commands
