/**
 * @file
 *
 * Implemention of FreeRTOS-CLI "task_stats" command.
 */

#include <string.h>

#include "FreeRTOS.h"
#include "FreeRTOS_CLI.h"
#include "task.h"

#include "console/commands.hpp"
#include "main.h"

namespace console::commands {

/* This function implements the behaviour of a command, so must have the correct
prototype. */
BaseType_t run_task_stats(
    char* write_buffer, size_t write_buffer_len, const char* command_string)
{
    /* For simplicity, this function assumes the output buffer is large enough
    to hold all the text generated by executing the vTaskList() API function,
    so the xWriteBufferLen parameter is not used. */
    UNUSED(write_buffer_len);

    const char header[] = "Task           State   Priority Stack   #\r\n";
    strncpy(write_buffer, header, sizeof(header) - 1);

    /* pcWriteBuffer is used directly as the vTaskList() parameter, so the table
    generated by executing vTaskList() is written directly into the output
    buffer. */
    vTaskList(write_buffer + sizeof(header) - 1);

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}

const CLI_Command_Definition_t task_stats
    = { "task_stats", "task_stats: Gives task statistics.\r\n", run_task_stats, 0 };

} // namespace console::commands
